Function exists check
DavidAnderson684/webp-convert pull request #2
Opened 2022-10-06 15:12 UTC by venkatraj

2022-10-10 15:18 UTC, DavidAnderson684 requested changes
I don't think this is the right approach (I explain in a separate comment).

2022-10-10 15:18 UTC, DavidAnderson684 commented on src/Convert/Converters/BaseTraits/DestinationPreparationTrait.php
> +			if (file_exists($destination)) {
Can this condition occur? If `file_put_contents()` didn't return false, then it is indicating that it succeeded.

2022-10-10 15:18 UTC, DavidAnderson684 commented on src/Convert/Converters/Cwebp.php
> +                    $cArg = (function_exists('escapeshellarg') ? escapeshellarg($cArg) : $cArg);
I don't think this makes sense. The method has the description "Use "escapeshellarg()" on all arguments in a commandline string of options." But the only realistic cases in which `escapeshellarg()` does not exist is if the hosting company has disabled it and also all other command-line functions. So, if we avoid a fatal error here, there will still be a fatal error later when the other command-line function (`shell_exec()`, or whatever) is called.

What we should do is detect the impossibility of calling command-line functions earlier, and abort the call early. At worst, the change here would introduce a security hole if the host had weirdly disabled `escapeshellarg()` but not `shell_exec()`.

2022-10-11 03:58 UTC, venkatraj commented on src/Convert/Converters/BaseTraits/DestinationPreparationTrait.php
> +			if (file_exists($destination)) {
Theoretically, yes this condition can't occur. But this is one of my `you know nothing Jon Snow` moment

It sometimes happens on Windows. Earlier we had this card 
https://trello.com/c/ou8R11Vg/1057-investigate-permission-issue-in-windows

Recently (after 3.2.9 release) I came across same issue (couldn't find the support thread url), So, I thought it doesn't hurt to add a file existence test.

2022-10-11 04:30 UTC, venkatraj commented on src/Convert/Converters/BaseTraits/DestinationPreparationTrait.php
> +			if (file_exists($destination)) {
Here is another example, it can happen
https://wordpress.org/support/topic/version-3-2-6-incompatible-with-elementor-plugin/#post-16082346

2022-10-11 10:09 UTC, venkatraj commented on src/Convert/Converters/Cwebp.php
> +                    $cArg = (function_exists('escapeshellarg') ? escapeshellarg($cArg) : $cArg);
I created an MR to bailout in such conditions. i.e. If shell functions are not available, the webp conversion testing will throw error. So, we can conclude that the server offers no webp conversion tools.
https://source.updraftplus.com/team-updraft/wp-optimize/-/merge_requests/1122

The MR is in testing queue, but if you could take a look and decide that the solution is good, I will revert these changes

2022-10-12 09:44 UTC, DavidAnderson684 commented on src/Convert/Converters/Cwebp.php
> +                    $cArg = (function_exists('escapeshellarg') ? escapeshellarg($cArg) : $cArg);
@venkatraj Ah, I had not previously understood that the dependency can't do anything without shell functions (though, I probably should have, since I don't know of any pure-PHP converters). So, yes, the proposal there, to just disable the WebP functionality, is best. (Though you might want to add something to the UI so that the user knows why it's not there).

I assume that means this PR is not needed - please correct me if I'm wrong.

2022-10-12 09:45 UTC, DavidAnderson684 submitted a review, later dismissed

2022-10-12 09:46 UTC, DavidAnderson684 commented on src/Convert/Converters/Cwebp.php
> +                    $cArg = (function_exists('escapeshellarg') ? escapeshellarg($cArg) : $cArg);
Ah, no, looks like some bits of the PR are still needed, sorry.

2022-10-20 14:18 UTC, DavidAnderson684 requested changes

2022-10-20 14:18 UTC, DavidAnderson684 commented on src/Convert/Converters/Cwebp.php
> +                    $cArg = (function_exists('escapeshellarg') ? escapeshellarg($cArg) : $cArg);
@venkatraj This line change should be reverted - if the security function is not available, it's better to crash than silently remove the security.

2022-10-20 14:18 UTC, DavidAnderson684 commented on src/Convert/Converters/Cwebp.php
> +                    $cArg = (function_exists('escapeshellarg') ? escapeshellarg($cArg) : $cArg);
(Same for the similar lines below).

2022-10-27 13:24 UTC, DavidAnderson684 approved these changes

2022-11-09 10:15 UTC, merged